name: Check that nlcnx*i5y4.onion is online every HOUR using the torssh action
on:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout github
      - name: Checkout submodules associated with this repo
        uses: textbook/git-checkout-submodule-action@1.0.0
      - name: Run SSH
        uses: nolim1t/actions/torssh@0.2.0
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USERHOST: ${{ secrets.USERHOST }}
          CMD: "date -R > nlcnx-i5y4-date-output.txt"
      - name: Copy nlcnx-i5y4-date-output.txt to working dir
        uses: nolim1t/actions/torscp@0.2.0
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SRC: ${{ secrets.USERHOST }}:nlcnx-i5y4-date-output.txt
          DEST: ./nlcnx-i5y4-date-output.txt
      - name: Add nlcnx-i5y4-date-output.txt to github
        run: git add nlcnx-i5y4-date-output.txt
      - name: Set up git config
        run: git config --global user.email "nolim1t@users.noreply.github.com" && git config --global user.name "@nolim1t"
      - name: Commit nlcnx-i5y4-date-output.txt to this repo
        run: git commit --allow-empty -m "Add output of date from nlcnx*i5y4.onion"
      - name: Update host key for github
        run: mkdir -p ~/.ssh && echo "${PRIVATE_KEY}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: Add SSH Target and push to upstream
        run: git remote add originssh git@github.com:nolim1t/actions.git && git push originssh master
