name: Test SSH Command on push
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run SSH
        uses: nolim1t/actions/torssh@master
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USERHOST: ${{ secrets.USERHOST }}
          CMD: ${{ secrets.CMD }}
